// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CommentListRequest struct {
	Id string `path:"postId"`
}

type CommentListResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    []CommentResponse `json:"data"`
}

type CommentResponse struct {
	Id        uint   `json:"id"`
	Content   string `json:"content"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	PostID    uint   `json:"post_id"`
	CreatedAt string `json:"created_at"`
}

type CreateCommentRequest struct {
	PostID  uint   `json:"post_id"`
	Content string `json:"content"`
}

type CreatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    TokenData `json:"data"`
}

type PostListResponse struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Data    []PostResponse `json:"data"`
}

type PostResponse struct {
	Id        uint   `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    UserData `json:"data"`
}

type SinglePostResponse struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    PostResponse `json:"data"`
}

type TokenData struct {
	Token string `json:"token"`
}

type UpdatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Id      string `path:"id"`
}

type DeletePostRequest struct {
	Id string `path:"id"`
}

type UserData struct {
	Id       uint   `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
type GetPostRequest struct {
	Id string `path:"id"`
}
type UserInfoResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    UserData `json:"data"`
}
