// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CommentListRequest struct {
	Id string `path:"postId"`
}

type CommentListResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    []CommentResponse `json:"data"`
}

type CommentResponse struct {
	Id        uint   `json:"id"`
	Content   string `json:"content"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	PostID    uint   `json:"post_id"`
	CreatedAt string `json:"created_at"`
}

type CreateCommentRequest struct {
	PostID  uint   `json:"post_id"`
	Content string `json:"content"`
}
type DeleteCommentRequest struct {
	Id string `path:"id"`
}

type CreatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    TokenData `json:"data"`
}

type PostListResponse struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Data    []PostResponse `json:"data"`
}

type PostResponse struct {
	Id        uint   `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    UserData `json:"data"`
}

type SinglePostResponse struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    PostResponse `json:"data"`
}

type TokenData struct {
	Token string `json:"token"`
}

type UpdatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Id      string `path:"id"`
}

type DeletePostRequest struct {
	Id string `path:"id"`
}

type UserData struct {
	Id       uint   `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
type GetPostRequest struct {
	Id string `path:"id"`
}
type UserInfoResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    UserData `json:"data"`
}

type RequestLogQueryRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Method   string `form:"method,optional"`
	Path     string `form:"path,optional"`
	Username string `form:"username,optional"`
	UserId   uint   `form:"userId,optional"`
}

type RequestLogResponse struct {
	ID         uint   `json:"id"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	StatusCode int    `json:"status_code"`
	Username   string `json:"username"`
	IPAddress  string `json:"ip_address"`
	UserID     uint   `json:"user_id"`
	UserAgent  string `json:"user_agent"`
	Request    string `json:"request"`
	Response   string `json:"response"`
	Error      string `json:"error"`
	Duration   int64  `json:"duration"`
	CreatedAt  string `json:"created_at"`
}

type RequestLogListResponse struct {
	Code     int                  `json:"code"`
	Message  string               `json:"message"`
	Data     []RequestLogResponse `json:"data"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"pageSize"`
	Total    int64                `json:"total"`
}
