// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CommentListResponse struct {
	BaseResponse
	Data []CommentResponse `json:"data"`
}

type CommentResponse struct {
	Id        uint   `json:"id"`
	Content   string `json:"content"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	PostID    uint   `json:"post_id"`
	CreatedAt string `json:"created_at"`
}

type CreateCommentRequest struct {
	PostID  uint   `json:"post_id"`
	Content string `json:"content"`
}

type CreatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginData struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type PostListResponse struct {
	BaseResponse
	Data []PostResponse `json:"data"`
}

type PostResponse struct {
	Id        uint   `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RegisterData struct {
	Id       uint   `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	BaseResponse
	Data     RegisterData `json:"data"`
	Id       uint         `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
}
type SinglePostResponse struct {
	BaseResponse
	Data PostResponse `json:"data"`
}

type UpdatePostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UserInfoData struct {
	Id       uint   `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserInfoResponse struct {
	Id       uint   `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
