// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "go-study/task4/internal/handler/user"
	"go-study/task4/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/comments",
				Handler: user.CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/comments/:id",
				Handler: user.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/posts",
				Handler: user.CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts",
				Handler: user.GetPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/posts/:id",
				Handler: user.UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/posts/:id",
				Handler: user.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id",
				Handler: user.GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:postId/comments",
				Handler: user.GetPostCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
