// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"go-study/task4/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/posts",
				Handler: getPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id",
				Handler: getPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:postId/comments",
				Handler: getPostCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: registerHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/comments",
				Handler: createCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/comments/:id",
				Handler: deleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/posts",
				Handler: createPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/posts/:id",
				Handler: updatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/posts/:id",
				Handler: deletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/info",
				Handler: userInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWT.AccessSecret),
	)
}
